### ISSUE TITLE
Nothing happen 48.2

### ISSUE THREAD

**Issue by morecrazyang** [eddiesigner/sketch-translate-me#1]
i from [this](https://github.com/eddiesigner/sketch-translate-me/wiki/Generate-a-Google-API-Key) and get a google API yet.
when i translate layer or artbords, it can copy one but no translate, the same as before.

**Comment by eddiesigner** [comment]
Please update the plugin to the version 0.1.1 and try again. Also please check the Google Cloud Translate API is enabled in your project, is valid and it doesn't have restrictions.

Do you know if the Sketch file was made with an old version of Sketch?

**Comment by eddiesigner** [comment]
I'll close this issue for now, if you have troubles feel free to open it again.
