### ISSUE TITLE
Google API Key Restrictions

### ISSUE THREAD

**Issue by smcelhinney** [eddiesigner/sketch-translate-me#2]
At the moment, this plugin requires a public Google Cloud Translation API key with no restrictions, how do I (as a Cloud Admin) restrict this key for use in this plugin only?

**Comment by eddiesigner** [comment]
I think that's not posible at the moment due you can only restrict the API key by URLs (websites), IP address (only servers), Android apps and iOS apps but not by Mac applications or something more specific like this plugin :/
